spring.application.name=DACN

server.port=${PORT:8080}

# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false


# CLOUDINARY
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.secure=true


# LOGGING
logbook.format.style=json
logbook.write.category=http-log

logging.level.http-log=TRACE
logging.level.org.zalando.logbook=TRACE
logging.level.org.springframework.web=TRACE

logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR


# FILE UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-milliseconds=900000

# REDIS AIVEN
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=6
spring.data.redis.ssl.enabled=true


# KAFKA AIVEN
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256

spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.consumer.group-id=ecommerce-ai-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.haui.event


# KAFKA TOPICS
app.kafka.topics.product-view=product-view-events
app.kafka.topics.cart-event=cart-events
app.kafka.topics.product-index=product-index-events
app.kafka.topics.chatbot-message=chatbot-message-events


# ANALYTICS
app.analytics.abandoned-cart-hours=24
app.analytics.rag-top-k=3


# AI DISABLED
app.ai.enabled=false

spring.ai.model.chat=none
spring.ai.model.embedding=none

# VNPAY
vnpay.tmn-code=MOSOMPYF
vnpay.hash-secret=${VNPAY_HASH_SECRET}
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=${VNPAY_RETURN_URL}
vnpay.version=2.1.0
vnpay.command=pay
vnpay.curr-code=VND
vnpay.locale=vn
vnpay.order-type=other