spring.application.name=DACN

spring.datasource.url=jdbc:mysql://localhost:3306/laptopshop?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=06102005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

cloudinary.cloud-name=dnrsb2d9v
cloudinary.api-key=811265134877191
cloudinary.api-secret=rnDEbjawOaKpQnLEow-zMAhQCuo
cloudinary.secure=true


# Logbook format JSON
logbook.format.style=json
logbook.write.category=http-log
logging.level.http-log=TRACE
logging.level.org.zalando.logbook=TRACE
logging.level.org.springframework.web=TRACE

logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Jwt(30')
app.jwt.secret=b2c138a6654022d7e4df6a26b7e37f898fd5c449c0354456de30db101ad206af
app.jwt.expiration-milliseconds=1800000